In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = "drive/My Drive/CombinedInput.xlsx"
df = pd.read_excel(path)

In [ ]:
df.head(3)

Unnamed: 0  A0A0B4J1X5    O00592  ...    Q9BWS9    Q9UM54    Q9Y625
0           1    0.482161  0.473002  ...  0.502206  0.399124  0.539576
1           1    0.611093  0.495021  ...  0.493575  0.488063  0.529156
2           1    0.544422  0.508639  ...  0.470651  0.472605  0.564230

[3 rows x 41 columns]

In [ ]:
df.columns

Index(['Unnamed: 0', 'A0A0B4J1X5', 'O00592', 'O15438', 'O75884', 'O95816',
       'P00747', 'P00966', 'P01861', 'P02652', 'P02671', 'P02675', 'P02679',
       'P02730', 'P02750', 'P02753', 'P02766', 'P05090', 'P08311', 'P08697',
       'P12429', 'P14923', 'P17677', 'P19652', 'P19827', 'P22105', 'P25311',
       'P25685', 'P26447', 'P35556', 'P39060', 'P54652', 'P61626', 'Q13510',
       'Q14126', 'Q15714', 'Q96CN7', 'Q96T23', 'Q9BWS9', 'Q9UM54', 'Q9Y625'],
      dtype='object')

In [ ]:
df.rename({'Unnamed: 0':'Labels'},axis = 1, inplace=True)

In [ ]:
df.head()

Labels  A0A0B4J1X5    O00592  ...    Q9BWS9    Q9UM54    Q9Y625
0       1    0.482161  0.473002  ...  0.502206  0.399124  0.539576
1       1    0.611093  0.495021  ...  0.493575  0.488063  0.529156
2       1    0.544422  0.508639  ...  0.470651  0.472605  0.564230
3       1    0.501175  0.522488  ...  0.472020  0.520375  0.529292
4       1    0.513616  0.603717  ...  0.477580  0.535413  0.521307

[5 rows x 41 columns]

In [ ]:
df.shape

(46, 41)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [ ]:
df.columns

Index(['Labels', 'A0A0B4J1X5', 'O00592', 'O15438', 'O75884', 'O95816',
       'P00747', 'P00966', 'P01861', 'P02652', 'P02671', 'P02675', 'P02679',
       'P02730', 'P02750', 'P02753', 'P02766', 'P05090', 'P08311', 'P08697',
       'P12429', 'P14923', 'P17677', 'P19652', 'P19827', 'P22105', 'P25311',
       'P25685', 'P26447', 'P35556', 'P39060', 'P54652', 'P61626', 'Q13510',
       'Q14126', 'Q15714', 'Q96CN7', 'Q96T23', 'Q9BWS9', 'Q9UM54', 'Q9Y625'],
      dtype='object')

In [ ]:
X = df.iloc[:,1:].values
y = df.iloc[:,0].values

In [ ]:
X

array([[0.48216094, 0.47300247, 0.50993487, ..., 0.50220551, 0.39912369,
        0.53957622],
       [0.61109321, 0.49502142, 0.61170552, ..., 0.49357527, 0.48806343,
        0.52915599],
       [0.5444217 , 0.50863902, 0.69981856, ..., 0.47065112, 0.47260506,
        0.56423002],
       ...,
       [0.57024314, 0.45268075, 0.61498703, ..., 0.42278861, 0.59261262,
        0.44881451],
       [0.58102336, 0.51905667, 0.57544172, ..., 0.42232669, 0.55824008,
        0.40849517],
       [0.4040198 , 0.37049642, 0.43537138, ..., 0.44545285, 0.50154852,
        0.47430849]])

In [ ]:
X.shape

(46, 40)

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [ ]:
y.shape

(46,)

In [ ]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 42)

# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (32, 40)
Training Labels Shape: (32,)
Testing Features Shape: (14, 40)
Testing Labels Shape: (14,)


In [ ]:
classifier = RandomForestClassifier(n_estimators=10, max_depth=5, max_features='sqrt', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)

result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.88      0.70         8
           1       0.50      0.17      0.25         6

    accuracy                           0.57        14
   macro avg       0.54      0.52      0.48        14
weighted avg       0.55      0.57      0.51        14

Accuracy: 0.5714285714285714


In [ ]:
# Making the Confusion Matrix
print(pd.crosstab(y_test, y_pred, rownames=['Actual'], colnames=['Predicted']))

Predicted  0  1
Actual         
0          7  1
1          5  1


In [ ]:
from sklearn.metrics import accuracy_score  
scores_classification = accuracy_score(y_test, y_pred)
print(scores_classification)

0.5714285714285714


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[7 1]
 [5 1]]


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
train_preds = classifier.predict(X_train)
mse = mean_squared_error(y_train, train_preds)
rmse = sqrt(mse)
rmse

0.1767766952966369

In [ ]:
test_preds = classifier.predict(X_test)
mse = mean_squared_error(y_test, test_preds)
rmse = sqrt(mse)
rmse

0.6546536707079771